# Generated by Django 3.0.6 on 2020-05-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
