# Generated by Django 3.0.6 on 2020-05-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200506_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
