# Generated by Django 3.0.6 on 2020-05-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200506_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
