# Generated by Django 3.0.6 on 2020-05-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200506_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='is_choose',
            field=models.BooleanField(default=False),
        ),
    ]
