# Generated by Django 3.0.6 on 2020-05-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_check_is_choose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='employee_no',
        ),
    ]
