# Generated by Django 3.0.6 on 2020-05-07 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0009_auto_20200507_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Professor'), (2, 'Dean'), (3, 'VPAA'), (4, 'admin')], null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
